name: "GitHub Pages"
on:
  push:
    branches: ["main"]

jobs:
  "build":
    name: "Build the docs"
    runs-on: ubuntu-latest
    steps:
    - name: "Checkout this repo"
      uses: actions/checkout@v3
    - name: "Setup Python"
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
        cache: "pip"
    - name: "Install pip dependencies"
      run: "pip install -r docs/requirements.txt"
    - name: "Build with Sphinx"
      run: "cd docs && make html"
    - name: "Upload GitHub Pages artifact"
      uses: actions/upload-pages-artifact@v1
      with:
        path: "./docs/_build/html"

  "deploy":
    name: "Deploy the docs to GitHub Pages"
    needs: "build"
    permissions:
        pages: write
        id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: "Deploy to GitHub Pages"
        id: deployment
        uses: actions/deploy-pages@v1
